about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: Tools for dealing with SAM and BAM files
build:
  number: 0
package:
  name: samtools
  version: 0.1.19
requirements:
  build:
    - ncurses
    - zlib
  run:
    - ncurses
    - zlib
source:
  git_url: 'https://github.com/samtools/samtools'
  git_rev: 'ccf1da91b29b75764402e20f46ec21fc293fe5f5'
test:
  commands:
    - "samtools view --help 2>&1 | grep Notes > /dev/null"
